name: "Terraform Workflow"
on:
  workflow_dispatch:

jobs:
  Plan_Dev:
    if: github.ref == 'refs/heads/dev'
    uses: pravishtsunil/wema-terraform/.github/workflows/aws_tf_plan.yml@main
    with:
      path: Terraform
      tf_vars_file: tfvars/dev/dev.tfvars
      gh_environment: dev
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}

  Deploy_Dev:
    needs: Plan_Dev
    uses: pravishtsunil/wema-terraform/.github/workflows/aws_tf_appy.yml@main
    with:
      path: Terraform
      tf_vars_file: tfvars/dev/dev.tfvars
      gh_environment: dev
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}

  Plan_Uat:
    if: github.ref == 'refs/heads/main'
    uses: pravishtsunil/wema-terraform/.github/workflows/aws_tf_plan.yml@main
    with:
      path: Terraform
      tf_vars_file: uat.tfvars
      gh_environment: uat
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}

  Deploy_Uat:
    needs: Plan_Uat
    uses: pravishtsunil/wema-terraform/.github/workflows/aws_tf_appy.yml@main
    with:
      path: Terraform
      tf_vars_file: uat.tfvars
      gh_environment: uat
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}