name: "Terraform Workflow"
on:
  workflow_dispatch:
  push:
    branches:
      - main

# These linter errors can be ignored as they are valid GitHub Actions syntax for reusable workflows
jobs:
  Plan_Dev:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    uses: pravishtsunil/wema-terraform/.github/workflows/aws_tf_plan.yml@main
    with:
      path: Terraform
      tf_vars_file: dev.tfvars
      gh_environment: dev
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}

  Deploy_Dev:
    needs: Plan_Dev
    runs-on: ubuntu-latest
    environment: dev
    uses: pravishtsunil/wema-terraform/.github/workflows/aws_tf_appy.yml@main
    with:
      path: Terraform
      tf_vars_file: tfvars/dev/dev.tfvars
      gh_environment: dev
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}

  Plan_Uat:
    if: github.ref == 'refs/heads/main'
    needs: Deploy_Dev
    runs-on: ubuntu-latest
    uses: pravishtsunil/wema-terraform/.github/workflows/aws_tf_plan.yml@main
    with:
      path: Terraform
      tf_vars_file: tfvars/uat/uat.tfvars
      gh_environment: uat
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}

  Deploy_Uat:
    needs: Plan_Uat
    runs-on: ubuntu-latest
    environment: uat
    uses: pravishtsunil/wema-terraform/.github/workflows/aws_tf_appy.yml@main
    with:
      path: Terraform
      tf_vars_file: tfvars/uat/uat.tfvars
      gh_environment: uat
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}

  Plan_Prod:
    if: github.ref == 'refs/heads/main'
    needs: Deploy_Uat
    runs-on: ubuntu-latest
    uses: pravishtsunil/wema-terraform/.github/workflows/aws_tf_plan.yml@main
    with:
      path: Terraform
      tf_vars_file: tfvars/prod/prod.tfvars
      gh_environment: prod
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}

  Deploy_Prod:
    needs: Plan_Prod
    runs-on: ubuntu-latest
    environment: prod
    uses: pravishtsunil/wema-terraform/.github/workflows/aws_tf_appy.yml@main
    with:
      path: Terraform
      tf_vars_file: tfvars/prod/prod.tfvars
      gh_environment: prod
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}