name: "Terraform Workflow"
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  actions: read

jobs:
  Plan_Dev:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    uses: pravishtsunil/wema-terraform/.github/workflows/aws_tf_plan.yml@main
    with:
      path: Terraform
      tf_vars_file: dev.tfvars
      gh_environment: dev
    secrets: inherit

  Plan_Uat:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    uses: pravishtsunil/wema-terraform/.github/workflows/aws_tf_plan.yml@main
    with:
      path: Terraform
      tf_vars_file: uat.tfvars
      gh_environment: uat
    secrets: inherit

  Plan_Prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    uses: pravishtsunil/wema-terraform/.github/workflows/aws_tf_plan.yml@main
    with:
      path: Terraform
      tf_vars_file: prod.tfvars
      gh_environment: prod
    secrets: inherit

  Deploy_Dev:
    needs: Plan_Dev
    runs-on: ubuntu-latest
    environment: dev
    uses: pravishtsunil/wema-terraform/.github/workflows/aws_tf_appy.yml@main
    with:
      path: Terraform
      tf_vars_file: dev.tfvars
      gh_environment: dev
    secrets: inherit

  Deploy_Uat:
    needs: Plan_Uat
    runs-on: ubuntu-latest
    environment: uat
    uses: pravishtsunil/wema-terraform/.github/workflows/aws_tf_appy.yml@main
    with:
      path: Terraform
      tf_vars_file: uat.tfvars
      gh_environment: uat
    secrets: inherit

  Deploy_Prod:
    needs: Plan_Prod
    runs-on: ubuntu-latest
    environment: prod
    uses: pravishtsunil/wema-terraform/.github/workflows/aws_tf_appy.yml@main
    with:
      path: Terraform
      tf_vars_file: prod.tfvars
      gh_environment: prod
    secrets: inherit